name: Check all links in the repository
on:
  schedule:
    - cron: '0 0 * * *'
  deployment_status:
  workflow_dispatch:

concurrency:
  group: link-check-${{ github.event.deployment.id || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
jobs:
  check:
    name: Check all links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Restore lychee cache
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Run Lychee
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.9.0
        with:
          args: >-
            --verbose --no-progress --max-concurrency 8 --retry-wait-time 20
            --cache --max-cache-age 2d --base-url ${{
            github.event.deployment.payload.web_url || 'https://doc.dvc.org' }}
            '.github/**/*' 'content/**/*' 'src/**/*'
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
